[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  SKIP_ENV_VALIDATION = "false"

[context.deploy-preview.environment]
  SKIP_ENV_VALIDATION = "true"

[context.branch-deploy.environment]
  SKIP_ENV_VALIDATION = "true"
