[build]
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"
  NEXT_PUBLIC_DEMO_MODE = "true"
  CSS_MINIMIZE = "true"
  DISABLE_TURBOPACK = "true"
  # Use a demo database URL for Netlify (you'll need to replace this with a real database)
  DATABASE_URL = "file:./dev.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  SKIP_ENV_VALIDATION = "false"
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"

[context.deploy-preview.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_DEMO_MODE = "true"

[context.branch-deploy.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"  
  NEXT_PUBLIC_DEMO_MODE = "true"

# Handle Next.js routing - removed incorrect redirect
