[build]
  command = "npm ci && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . --"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"
  NEXT_PUBLIC_DEMO_MODE = "true"
  # Force Netlify to use Node.js only, ignore Python files
  NETLIFY_SKIP_PYTHON = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  SKIP_ENV_VALIDATION = "false"
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"

[context.deploy-preview.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_DEMO_MODE = "true"

[context.branch-deploy.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"  
  NEXT_PUBLIC_DEMO_MODE = "true"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
