[build]
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"
  NEXT_PUBLIC_DEMO_MODE = "true"
  CSS_MINIMIZE = "true"
  DISABLE_TURBOPACK = "true"
  # No DATABASE_URL in demo mode - database operations will be mocked

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Configure Netlify Functions for tRPC API endpoints
  # Increase timeout for AI/LLM operations that might take longer
  timeout = 300
  max_duration = 300

[context.production.environment]
  SKIP_ENV_VALIDATION = "false"
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"

[context.deploy-preview.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_DEMO_MODE = "true"

[context.branch-deploy.environment]
  SKIP_ENV_VALIDATION = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://learnstellation.onrender.com"  
  NEXT_PUBLIC_DEMO_MODE = "true"

# Handle Next.js routing - removed incorrect redirect
