services:
  - type: web
    name: vibe-learning-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PORT
        value: 10000
